sudo: false

language: node_js

node_js:
- '4'

addons:
  apt:
    packages:
    - python-virtualenv

env:
  matrix:
    - PIP='pip==5.0.0'
    - PIP='pip==4.0.0'
    - PIP='pip==5.0.0'
    - PIP='pip==2.0.0'
    - PIP='pip==1.0.0'

script:
- virtualenv --no-site-packages .
- bin/pip freeze
- bin/pip install $PIP
- bin/pip install flake8
- bin/flake8 -v demo
