sudo: false

language: node_js

node_js:
- '4'
- '6'

addons:
  apt:
    packages:
    - python-virtualenv

script:
- flake8 demo
- virtualenv --no-site-packages .
- bin/pip install 'pip==8.1.2' 'setuptools==21.1.0'
- bin/pip install flake8
- bin/flake8 demo
