sudo: false

language: node_js

node_js:
- '4'

addons:
  apt:
    packages:
    - python-virtualenv

script:
- virtualenv --no-site-packages .
- bin/pip install 'pip==8.1.2'
- bin/pip install flake8
- bin/flake8 demo
