---

sudo: required

addons:
  apt:
    packages:
      - python3-netifaces

script:
  - sudo mkdir -p /var/sig
  - sudo chmod +rw /var/sig
  - echo test >> /var/sig/amazonses_smtp.txt
  - echo test >> /var/sig/amazonses_smtp.txt
  - echo test >> /var/sig/amazonses_smtp.txt
  - echo test >> /var/sig/amazonses_smtp.txt
  - ./docker-run --share=/var/sig make --makefile=demo.mk checks
