---

sudo: false

addons:
  apt:
    packages:
      - python3-netifaces

env:
  global:
    - DOCKER_USERNAME=dockerhubc2c
    - secure: "vpSNV7FOz6TaULaqqEfviKizsUnROqBKGEurvM2D/02mQQgINl5BRDuZMyCiPB+m96hbbO4IDxuO3r9Fvnsn3faDrze/z\
        jKC+/npztumqNYr8wSDwwwiArQQrYbY+nSQoswv5xYPKVRhTKsbtvYHqIG3c+1cgSQ5ODsvbZTWQXM="
    - OPENSHIFT_URL=https://openshift-ch-3.camptocamp.com/
    - OPENSHIFT_USERNAME=pvalsecchi
    - secure: "XFk3jPtVYaYEwWgo6aA3JhrbruBzGgN6lQzXrYla9XhmmTuLX0S40SQk5iBakDosNOMhy9ys6bL8V1uhcOtzcY8V52U7s\
        uDN9odk95focG+2epgPuslOtDsXHVZ1fD/ErKTepE1qioIqqGmXLx3+Ol6oABPso7Ety75BtctBxa0="

jobs:
  include:
    - stage: config-geoportal
      script:
        - docker run --name python --detach camptocamp/tilecloud-chain:1.9 sleep 9999
        - docker exec python python3 -m pip install c2c-template
        - docker cp tilegeneration/config.yaml.tmpl python:/tmp
        - docker exec python mkdir mapcache
        - docker exec python generate_controller --config=/tmp/config.yaml.tmpl --generate-mapcache-config --mapcache-version=1.6
        - mkdir mapcache
        - docker cp python:/etc/tilegeneration/mapcache/mapcache.xml.tmpl mapcache/mapcache.xml.tmpl
        - docker build --tag=camptocamp/demo-config:latest .
      after_success:
        - ./travis/deploy 2.4 config
    - script:
        - ./docker-run make checks
        - ./docker-run make docker-build-geoportal
      after_success:
        - ./travis/deploy 2.4 geoportal
