---

sudo: false

addons:
  apt:
    packages:
      - python3-netifaces

script:
  - echo test >> /var/sig/amazonses_smtp.txt
  - echo test >> /var/sig/amazonses_smtp.txt
  - echo test >> /var/sig/amazonses_smtp.txt
  - echo test >> /var/sig/amazonses_smtp.txt
  - ./docker-run --share=/var/sig make --makefile=demo.mk checks
