---

# The project Docker compose file for development.

version: '2'

services:
  config:
    extends:
      file: docker-compose-lib.yaml
      service: config
    environment:
      - TILEGENERATION_S3_BUCKET
      - OSM_PGDATABASE
      - RASTER_BASE_PATH

  mapserver:
    extends:
      file: docker-compose-lib.yaml
      service: mapserver
    mem_limit: 128M
    volumes_from:
      - config:rw
    volumes:
      - /var/sig:/var/sig:ro

  qgisserver:
    image: camptocamp/geomapfish-qgisserver:gmf2.4-qgismaster
    extends:
      file: docker-compose-lib.yaml
      service: qgisserver
    mem_limit: 1G
    volumes_from:
      - config:ro
    environment:
      # Single QGIS project files
      QGIS_PROJECT_FILE: /etc/qgisserver/project.qgz
      GEOMAPFISH_OGCSERVER: <OGC server name>
      # Multiple QGIS project files
      # QGIS_PROJECT_FILE:
      # GEOMAPFISH_ACCESSCONTROL_CONFIG: /etc/qgisserver/accesscontrol_config.yaml

  tinyows:
    extends:
      file: docker-compose-lib.yaml
      service: tinyows
    mem_limit: 32M
    volumes_from:
      - config:ro

  mapcache:
    extends:
      file: docker-compose-lib.yaml
      service: mapcache
    mem_limit: 256M
    volumes_from:
      - config:ro

  memcached:
    extends:
      file: docker-compose-lib.yaml
      service: memcached
    mem_limit: 128M

  redis:
    extends:
      file: docker-compose-lib.yaml
      service: redis
    mem_limit: 64M

  tilecloudchain:
    extends:
      file: docker-compose-lib.yaml
      service: tilecloudchain
    mem_limit: 256M
    environment:
      - AWS_DEFAULT_REGION
    volumes_from:
      - config:ro

  tilegeneration_slave:
    extends:
      file: docker-compose-lib.yaml
      service: tilegeneration_slave
    mem_limit: 128M
    volumes_from:
      - config:ro
    environment:
      - AWS_DEFAULT_REGION

  geoportal:
    extends:
      file: docker-compose-lib.yaml
      service: geoportal
    mem_limit: 512M
    environment:
      - OSM_PGDATABASE
      - RASTER_BASE_PATH
      - AWS_DEFAULT_REGION
      - AWS_S3_ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SMTP_USER
      - SMTP_PASSWORD
    volumes:
      - /var/sig:/var/sig:ro

  alembic:
    extends:
      file: docker-compose-lib.yaml
      service: alembic

  front:
    extends:
      file: docker-compose-lib.yaml
      service: front
    mem_limit: 16M
    volumes_from:
      - config:ro
## if docker_global_front:
##     networks:
##       default: {}
##       global:
##         aliases:
##           - ${instance}

## networks:
##   default: {}
##   global:
##     external:
##       name: global_default
## endif
