---

# A compose file for the build.

version: '2'

volumes:
  build:
    external:
      name: ${BUILD_VOLUME_NAME}

services:
  config:
    image: ${DOCKER_BASE}-config:${DOCKER_TAG}

  mapserver:
    extends:
      file: docker-compose-lib.yaml
      service: mapserver
    volumes_from:
      - config:rw

  qgisserver:
    image: camptocamp/geomapfish-qgisserver:gmf2.4-qgis3.4
    extends:
      file: docker-compose-lib.yaml
      service: qgisserver
    mem_limit: 1G
    volumes_from:
      - config:ro
    environment:
      # Single QGIS project files
      QGIS_PROJECT_FILE: /etc/qgisserver/project.qgz
      GEOMAPFISH_OGCSERVER: QGIS server
      # Multiple QGIS project files
      # QGIS_PROJECT_FILE:
      # GEOMAPFISH_ACCESSCONTROL_CONFIG: /etc/qgisserver/accesscontrol_config.yaml

  build:
    extends:
      file: docker-compose-lib.yaml
      service: build
    environment:
      - OSM_PGDATABASE
