---

version: 2
jobs:

  config:
    docker:
      - image: circleci/python:3
    environment:
      - DOCKER_USERNAME=dockerhubc2c
      - OPENSHIFT_URL=https://openshift-ch-3.camptocamp.com/
      - OPENSHIFT_USERNAME=sbrunner
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build --config .env.sample
      - deploy:
          command: scripts/publish-docker 2.4 config

  geoportal:
    machine:
      docker_layer_caching: true
    environment:
      - DOCKER_USERNAME=dockerhubc2c
      - OPENSHIFT_URL=https://openshift-ch-3.camptocamp.com/
      - OPENSHIFT_USERNAME=sbrunner
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build --geoportal .env.sample
      - deploy:
          command: scripts/publish-docker 2.4 geoportal

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - config
      - geoportal
